const LOCALURL = "http://mpetdb.citasgoo.cn/"
const URL = {
    getToken:LOCALURL+'token/getToken',//获取图片上传token的接口
    getCategoryList:LOCALURL+'goods/getCategoryList',//获取所有分类大类
    getOneCategory:LOCALURL+'goods/getOneCategory',//获取某个分类大类
    addCategory:LOCALURL+'goods/addCategory',//添加某个分类大类
    updateOneCategory:LOCALURL+'goods/updateOneCategory',//修改某个大类信息
    getCategorySubList:LOCALURL+'goods/getCategorySubList',//获取某大类的所有小类
    deleteCategory:LOCALURL+'goods/deleteCategory',//删除某个大类
    deleteAllCategorySub:LOCALURL+'goods/deleteAllCategorySub',//删除此大类下的所有小类
    deleteGoodsOFCategory:LOCALURL+'goods/deleteGoodsOFCategory',//删除此大类下的所有商品
    deleteGoodsOFCategorySub:LOCALURL+'goods/deleteGoodsOFCategorySub',//删除此小类下的所有商品
    deteleCategorySub:LOCALURL+'goods/deteleCategorySub',//删除某个小类
    addOneCategorySub:LOCALURL+'goods/addOneCategorySub',//添加一个小类
    addGoods:LOCALURL+'goods/addGoods',//添加商品
    getGoodsCategoryList:LOCALURL+'goods/getGoodsCategoryList',//所有商品大类
    getAllGoods:LOCALURL+'goods/getAllGoods',//获得所有商品
    changeGoodsState:LOCALURL+'goods/changeGoodsState',//上下架商品
    findGoodsByName:LOCALURL+'goods/findGoodsByName',//根据名字模糊查找商品
    findGoodsByID:LOCALURL+'goods/findGoodsByID',//根据id查找商品
    deleteOneGoods:LOCALURL+'goods/deleteOneGoods',//删除一个商品
    updateGoods:LOCALURL+'goods/updateGoods',//修改商品信息
    getAllService:LOCALURL+'goods/getAllService',//获得所有服务
    addService:LOCALURL+'goods/addService',//添加一个服务
    updateService:LOCALURL+'goods/updateService',//修改服务信息
    findServiceByName:LOCALURL+'goods/findServiceByName',//根据名字模糊查找服务
    findServiceByID:LOCALURL+'goods/findServiceByID',//根据id查找服务
    getServiceCategoryList:LOCALURL+'goods/getServiceCategoryList',//查找服务大类
    findAllShare:LOCALURL+'sharepet/findAllShare',//查找所有宠圈
    deteleShare:LOCALURL+'sharepet/deteleShare',//删除一条宠圈
    searchCqByName:LOCALURL+'sharepet/searchCqByName',//根据内容查找宠圈
    findAllUsers:LOCALURL+'user/findAllUsers',//查找所有用户
    searchUserById:LOCALURL+'user/searchUserById',//根据用户id查找用户
    searchUserByName:LOCALURL+'user/searchUserByName',//根据用户名查找用户
    findUserInfo:LOCALURL+'user/findUserInfo',//查收一个用户信息
    findPetInfo:LOCALURL+'pet/findPetInfo',//查收用户的宠物信息
    getUserAddress:LOCALURL+'address/getUserAddress',//查收用户收货地址
    findAllGoodsOrder:LOCALURL+'goodsorder/findAllGoodsOrder',//查找所有商品订单
    findOrderByID:LOCALURL+'goodsorder/findOrderByID',//根据id查找订单
    findOrderByLogistics:LOCALURL+'goodsorder/findOrderByLogistics',//根据订单状态查找订单
    findAllServiceOrder:LOCALURL+'orderservice/findAllServiceOrder',//查找所有服务订单
    findServiceOrderByID:LOCALURL+'orderservice/findServiceOrderByID',//根据id查找订单
    findServiceOrderByLogistics:LOCALURL+'orderservice/findServiceOrderByLogistics',//根据订单状态查找订单
    getAllComments:LOCALURL+'comments/getAllComments',//查找所有评论
    changeCommentPass:LOCALURL+'comments/changeCommentPass',//审核评论
    findCommentsOfGoods:LOCALURL+'comments/findCommentsOfGoods',//查找某个商品的评论
    findCommentsByStatus:LOCALURL+'comments/findCommentsByStatus',//查找某状态的所有评论
    addNotice:LOCALURL+'notice/addNotice',//添加公告
    getAllNotice:LOCALURL+'notice/getAllNotice',//查找所有公告
    deleteNotice:LOCALURL+'notice/deleteNotice',//删除公告
    login:LOCALURL+'admin/login',//管理员登录
    deleteGoodsOfNone:LOCALURL+'cart/deleteGoodsOfNone',//删除购物车商品
    searchUserImgByID:LOCALURL+'user/searchUserImgByID',//根据id查找用户头像
    searchUserNameByID:LOCALURL+'user/searchUserNameByID',//根据id查找用户名
    sendGoods:LOCALURL+'goodsorder/sendGoods',//一键发货
    findOneCategory:LOCALURL+'goods/findOneCategory',
    getData:LOCALURL+'data/getData',//获取统计数据
}
module.exports = URL